//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceYear
    {
        public int AttendanceYearId { get; set; }
        public string AttendanceYearName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> MarkedAsDelete { get; set; }
        public string Series { get; set; }
        public Nullable<int> PrevFYId { get; set; }
        public Nullable<int> NextFYId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Company Company { get; set; }
    }
}
