//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int Logid { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string Action { get; set; }
        public int userid { get; set; }
        public string UserName { get; set; }
        public int UserRoleNo { get; set; }
        public int y_id { get; set; }
        public string SoftwareVersion { get; set; }
        public int SessionId { get; set; }
        public string MachineIP { get; set; }
        public string MachineNo { get; set; }
    }
}
