//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodGroup
    {
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public int MarkedAsDelete { get; set; }
    }
}
