//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarStatu
    {
        public int CalendarStatusId { get; set; }
        public string CalendarStatus { get; set; }
        public string StatusFor { get; set; }
    }
}
