//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompOffApplication
    {
        public int CompOffId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<int> FromDateStatus { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> ToDateStatus { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public string RejectReason { get; set; }
        public string ExtrasHoursDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int MarkedAsDelete { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedOn { get; set; }
        public Nullable<int> SanctionedBy { get; set; }
        public Nullable<System.DateTime> SanctionedOn { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<int> AttendanceYearId { get; set; }
    }
}
