//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondoneTrn
    {
        public int CondoneId { get; set; }
        public string ShiftId { get; set; }
        public int TransportId { get; set; }
        public System.DateTime CondoneDate { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string LateEarly { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string Employeelist { get; set; }
        public int MarkedAsDelete { get; set; }
        public Nullable<int> AttendanceYearId { get; set; }
        public Nullable<int> AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedOn { get; set; }
        public Nullable<int> SanctionBy { get; set; }
        public Nullable<System.DateTime> SanctionedOn { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Company Company { get; set; }
    }
}
