//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumulativeManualCompOff
    {
        public int CMCompOffId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ExtraWorkingHrs { get; set; }
        public string CompOffPurpose { get; set; }
        public int StatusId { get; set; }
        public double CompOffBalance { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public string RejectReason { get; set; }
        public int MarkedAsDelete { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<int> IsAutoEntry { get; set; }
        public Nullable<bool> IsOutPunchInNextDay { get; set; }
        public Nullable<bool> IsInPunchInNextDay { get; set; }
        public Nullable<int> CompOffHours { get; set; }
        public Nullable<bool> IsWeekDay { get; set; }
        public Nullable<bool> IsWeekOff { get; set; }
        public Nullable<bool> IsPaidHoliday { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedOn { get; set; }
        public Nullable<int> SanctionedBy { get; set; }
        public Nullable<System.DateTime> SanctioedOn { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<int> AttendanceYearId { get; set; }
    }
}
