//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumulativeCompOff
    {
        public int CompOffId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime WoDate { get; set; }
        public Nullable<System.DateTime> CoDate { get; set; }
        public string ShiftId { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime LogOutTime { get; set; }
        public Nullable<System.DateTime> TotalHrs { get; set; }
        public Nullable<int> CoHours { get; set; }
        public string DayStatus { get; set; }
        public string Remark { get; set; }
        public string RejectReason { get; set; }
        public string AppStatus { get; set; }
        public string WrkDayStatus { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> CompOffApplicationID { get; set; }
        public Nullable<int> ManualCompOffId { get; set; }
        public Nullable<int> BalanceCoHours { get; set; }
        public Nullable<int> UsedCoHours { get; set; }
        public Nullable<int> AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedOn { get; set; }
        public Nullable<int> SanctionedBy { get; set; }
        public Nullable<System.DateTime> SanctionedOn { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<int> AttedanceYearId { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
    }
}
