//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTransaction
    {
        public int DailyTrnId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime TranDate { get; set; }
        public string ShiftId { get; set; }
        public System.DateTime Login { get; set; }
        public System.DateTime LogOut { get; set; }
        public Nullable<System.DateTime> Login1 { get; set; }
        public Nullable<System.DateTime> LogOut1 { get; set; }
        public Nullable<System.DateTime> Early { get; set; }
        public Nullable<System.DateTime> Late { get; set; }
        public Nullable<System.DateTime> WorkingHrs { get; set; }
        public Nullable<System.DateTime> ExtraHrs { get; set; }
        public string SanctionedCOHrs { get; set; }
        public string Status { get; set; }
        public string ActualStatus { get; set; }
        public Nullable<System.DateTime> OTInTime { get; set; }
        public Nullable<System.DateTime> OTOutTime { get; set; }
        public Nullable<System.DateTime> PreviousLogin { get; set; }
        public Nullable<System.DateTime> PreviousLogOut { get; set; }
        public Nullable<System.DateTime> PreviousLogin1 { get; set; }
        public Nullable<System.DateTime> PreviousLogOut1 { get; set; }
        public string PreviousShiftId { get; set; }
        public string TStatus { get; set; }
        public string PostinFlag { get; set; }
        public string Lock { get; set; }
        public string Remark { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> LateCount { get; set; }
        public Nullable<bool> LeaveDeducted { get; set; }
        public string LeaveTypeDeducted { get; set; }
        public Nullable<int> EarlyCount { get; set; }
        public Nullable<decimal> ProcessDayValue { get; set; }
        public Nullable<int> MonthlySalaryMasterId { get; set; }
        public string PayrollDayValue { get; set; }
        public Nullable<int> AttendanceYearId { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
    }
}
