//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeclaredHoliday
    {
        public int DeclaredHolidayId { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public bool Type { get; set; }
        public System.DateTime CompWorkDay1 { get; set; }
        public Nullable<System.DateTime> CompWorkDay2 { get; set; }
        public string Description { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> MarkASDelete { get; set; }
        public Nullable<int> AttendanceYearId { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
