//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExtraDetail
    {
        public int EmployeeDetailID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Qualification { get; set; }
        public string PFNo { get; set; }
        public string BankAccountNo { get; set; }
        public string ESICNo { get; set; }
        public string LaptopNo { get; set; }
        public string OtherPaasingYear { get; set; }
        public string HSCPassingYear { get; set; }
        public string GraduationPassingYear { get; set; }
        public string PostGraduationPassingYear { get; set; }
        public string ExperienceBeforeFlagship { get; set; }
        public string ExperienceWithFlagship { get; set; }
        public string EmployeeCode { get; set; }
        public string GraduationQualification { get; set; }
        public string PostGraduationQualification { get; set; }
        public string OtherGraduationQualification { get; set; }
        public Nullable<System.DateTime> LeaveEffectiveFromDate { get; set; }
    }
}
