//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeIntimeshift
    {
        public string Employeecode { get; set; }
        public System.DateTime cmndate { get; set; }
        public Nullable<System.DateTime> Mintime { get; set; }
        public Nullable<System.DateTime> Maxtime { get; set; }
        public Nullable<int> punchcount { get; set; }
        public int CompanyId { get; set; }
        public string SHIFT { get; set; }
    }
}
