//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLifeCycle
    {
        public int LifeCycleId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> ResignedOn { get; set; }
        public Nullable<System.DateTime> ResignationAcceptedOn { get; set; }
        public Nullable<System.DateTime> AppointmentAcceptedOn { get; set; }
        public Nullable<bool> AppointmentLetterIssued { get; set; }
        public Nullable<bool> ConfirmLetterIssued { get; set; }
        public Nullable<bool> RelievingLetterissued { get; set; }
        public Nullable<bool> ExpLetterIssue { get; set; }
        public Nullable<System.DateTime> ServiceAgree { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LoggedInUser { get; set; }
        public Nullable<bool> ResignationAcceptedOrNot { get; set; }
        public string ResignationReason { get; set; }
    }
}
