//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeadCode()
        {
            this.Rules = new HashSet<Rule>();
        }
    
        public string HeadCodeId { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public string HeadCodeTypeFlag { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Company Company { get; set; }
        public virtual HeadType HeadType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rule> Rules { get; set; }
    }
}
