//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoliDay
    {
        public int HoliDayId { get; set; }
        public string HLType { get; set; }
        public int EmployeeId { get; set; }
        public int ReligionId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Criteria { get; set; }
        public string Description { get; set; }
        public int DayStatus { get; set; }
        public int CompanyId { get; set; }
        public int Branchid { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public int MarkedAsDelete { get; set; }
    }
}
