//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveMaster
    {
        public string LeaveCode { get; set; }
        public string LeaveName { get; set; }
        public string LeaveDescription { get; set; }
        public Nullable<double> NoOfDaysAllowedInYear { get; set; }
        public Nullable<double> MaxNoOfTimesAllowedInYear { get; set; }
        public Nullable<double> MaxNoOfLeavesAllowedAtaTime { get; set; }
        public Nullable<double> MaxNoOfLeavesAllowedInMonth { get; set; }
        public Nullable<bool> AccumulationAllowedOrNot { get; set; }
        public Nullable<double> MaxAccumulationDays { get; set; }
        public Nullable<bool> EncashmentAllowedOrNot { get; set; }
        public Nullable<double> NoOfDaysEncashed { get; set; }
        public Nullable<bool> NegativeBalanceAllowed { get; set; }
        public Nullable<bool> IsCarryForword { get; set; }
        public Nullable<bool> WOBetLevConsiderLeave { get; set; }
        public Nullable<bool> HHBetLevConsiderLeave { get; set; }
        public Nullable<bool> ISHalfAllowed { get; set; }
        public int BranchId { get; set; }
        public Nullable<bool> LeaveType { get; set; }
        public Nullable<int> LeaveCreditTypeId { get; set; }
        public string ApplicableToMaleFemale { get; set; }
        public int LeaveId { get; set; }
        public Nullable<bool> IsLeaveCombination { get; set; }
        public Nullable<double> MinNoofLeaveAllowedatatime { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public int MarkedAsDelete { get; set; }
        public Nullable<bool> IsInsufficientBalAllowed { get; set; }
        public Nullable<bool> IsPendingLeaveConsider { get; set; }
        public Nullable<bool> IsAttachmentNeeded { get; set; }
        public Nullable<double> AttachmentRequiredForMinNoOfLeave { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual EmployeeGroup EmployeeGroup { get; set; }
    }
}
