//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication
    {
        public int LeaveApplicationId { get; set; }
        public int EmployeeId { get; set; }
        public string LeaveType { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<int> FromDayStatus { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> ToDayStatus { get; set; }
        public Nullable<double> AppliedDays { get; set; }
        public Nullable<double> ActualDays { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public string RejectReason { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int MarkedAsDelete { get; set; }
        public Nullable<bool> IsPostSandwichCase { get; set; }
        public Nullable<bool> IsLWP { get; set; }
        public Nullable<double> LWP { get; set; }
        public Nullable<double> TotalDeductableDays { get; set; }
        public Nullable<double> LeaveConsumed { get; set; }
        public Nullable<bool> IsPreSandwichCase { get; set; }
        public Nullable<double> PreSandwichdays { get; set; }
        public Nullable<double> PostSandwichdays { get; set; }
        public Nullable<int> PreSandwichCaseLeaveID { get; set; }
        public Nullable<int> PostSandwichCaseLeaveID { get; set; }
        public string DocPath { get; set; }
        public string DocFileName { get; set; }
        public string DocFolder { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string LeaveAddress { get; set; }
        public string AltContactNo { get; set; }
        public Nullable<int> AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedOn { get; set; }
        public Nullable<int> SanctionedBy { get; set; }
        public Nullable<System.DateTime> SanctionedOn { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<int> AttendanceYearId { get; set; }
    }
}
