//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveEncash
    {
        public int LeaveEncashId { get; set; }
        public int EmployeeId { get; set; }
        public int FinancialYearId { get; set; }
        public string LeaveCode { get; set; }
        public string Status { get; set; }
        public double EncashValue { get; set; }
        public string RejectReason { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public int MarkedAsDelete { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> EncashDate { get; set; }
    }
}
