//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBalance
    {
        public int LeaveBalanceId { get; set; }
        public int EmployeeId { get; set; }
        public string LeaveType { get; set; }
        public Nullable<double> PreviousBalance { get; set; }
        public Nullable<double> CurrentBalance { get; set; }
        public Nullable<double> LeaveUsed { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> FinacialYearId { get; set; }
        public Nullable<int> AttendanceYearId { get; set; }
    }
}
