//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCredit
    {
        public int LeaveCreditId { get; set; }
        public int EmployeeId { get; set; }
        public int FinancialYearId { get; set; }
        public string LeaveType { get; set; }
        public Nullable<double> Availed { get; set; }
        public Nullable<double> CarryForward { get; set; }
        public Nullable<double> Encash { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public Nullable<System.DateTime> ApplicableEffectiveDate { get; set; }
        public Nullable<System.DateTime> ApplicableEffectiveEndDate { get; set; }
    }
}
