//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthDetail
    {
        public string MonthName { get; set; }
        public int NoOdDays { get; set; }
        public int Id { get; set; }
    }
}
