//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavMenu
    {
        public int navmenuId { get; set; }
        public int parId { get; set; }
        public string navmenuname { get; set; }
        public string description { get; set; }
        public string navlink { get; set; }
        public int srno { get; set; }
        public string active { get; set; }
        public string Icon { get; set; }
    }
}
