//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsId { get; set; }
        public string Type { get; set; }
        public string Info { get; set; }
        public System.DateTime NewsDate { get; set; }
        public Nullable<int> EmployeeGroupId { get; set; }
        public string NewsFor { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> NewsEndDate { get; set; }
        public Nullable<int> FinacialYearId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
