//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public Nullable<int> FromID { get; set; }
        public Nullable<int> ToID { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<bool> ReadFlag { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public string NotificationContent { get; set; }
        public Nullable<int> AttendanceYearId { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
    }
}
