//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODLateEarly
    {
        public int ODTourId { get; set; }
        public int EmployeeId { get; set; }
        public string ODTourType { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> ODDayStatus { get; set; }
        public double AppliedDay { get; set; }
        public double ActualDay { get; set; }
        public string Place { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public string OdTourHeadCode { get; set; }
        public string RejectReason { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string TransportType { get; set; }
        public Nullable<int> JourneyType { get; set; }
        public int MarkedAsDelete { get; set; }
        public Nullable<int> ODDayStatus1 { get; set; }
        public Nullable<System.DateTime> ODLoginTime { get; set; }
        public Nullable<System.DateTime> ODLogOutTime { get; set; }
        public Nullable<bool> IsInPunchInNextDay { get; set; }
        public Nullable<bool> IsOutPunchInNextDay { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string PurposeDescription { get; set; }
        public string ClientName { get; set; }
        public string CustomerName { get; set; }
        public string CSRNo { get; set; }
        public Nullable<int> AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedOn { get; set; }
        public Nullable<int> SanctionedBy { get; set; }
        public Nullable<System.DateTime> SanctionedOn { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<int> AttendanceYearId { get; set; }
    }
}
