//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtHr
    {
        public int OtId { get; set; }
        public Nullable<int> OtEmpId { get; set; }
        public Nullable<System.DateTime> OtTranDate { get; set; }
        public Nullable<System.DateTime> OtExtraHrs { get; set; }
        public Nullable<int> OtStatusId { get; set; }
        public Nullable<int> OtDesignationId { get; set; }
        public Nullable<int> OtBranchId { get; set; }
        public Nullable<int> OtCompanyId { get; set; }
        public Nullable<System.DateTime> OtEffectiveDate { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogOutTime { get; set; }
        public string Shift { get; set; }
    }
}
