//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESENTEMPLOYEE
    {
        public string employeecode { get; set; }
        public int Employeeid { get; set; }
        public Nullable<System.DateTime> Mintime { get; set; }
        public Nullable<System.DateTime> maxtime { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public Nullable<System.DateTime> PrevInTime { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CmnDate { get; set; }
        public string SHIFT { get; set; }
        public Nullable<System.DateTime> Workinghrs { get; set; }
        public Nullable<System.DateTime> Extrahrs { get; set; }
    }
}
