//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREVEMPINOUT
    {
        public string EmployeeCode { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> CmnDate { get; set; }
        public Nullable<System.DateTime> MinTime { get; set; }
        public Nullable<System.DateTime> MaxTime { get; set; }
        public Nullable<int> punchcount { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public Nullable<System.DateTime> PrevInTime { get; set; }
        public string PrevFlag { get; set; }
        public string SHIFT { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> Workinghrs { get; set; }
        public Nullable<System.DateTime> Extrahrs { get; set; }
    }
}
