//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleNavMenu
    {
        public int rnmId { get; set; }
        public int roleId { get; set; }
        public int y_id { get; set; }
        public int navmenuId { get; set; }
        public int displayOrder { get; set; }
    }
}
