//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int RuleId { get; set; }
        public string RuleName { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<decimal> SerialNo { get; set; }
        public string RuleDataType { get; set; }
    
        public virtual HeadCode HeadCode { get; set; }
        public virtual HeadType HeadType { get; set; }
        public virtual RuleFlag RuleFlag { get; set; }
    }
}
