//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedular
    {
        public int ScheduleId { get; set; }
        public string SchedularName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ScheduleType { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> FrequencyInMin { get; set; }
        public Nullable<int> RepeatCycle { get; set; }
        public Nullable<bool> SchedularStatus { get; set; }
    }
}
