//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftPatternRule
    {
        public int ShiftPatternRuleId { get; set; }
        public string ShiftPatternName { get; set; }
        public string ShiftPatternShortName { get; set; }
        public string ShiftPatternDescription { get; set; }
        public int WeekRuleId { get; set; }
        public decimal NoofDays { get; set; }
        public string DayPattern { get; set; }
        public string ShiftPattern { get; set; }
    }
}
