//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftSwapReplace
    {
        public int ShiftSRId { get; set; }
        public int FromEmployeeId { get; set; }
        public Nullable<int> ToEmployeeId { get; set; }
        public string ShiftId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string ApplyFor { get; set; }
        public string Status { get; set; }
        public string RejectReason { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
    }
}
