//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public string ShiftCode { get; set; }
        public string ShiftName { get; set; }
        public string ShiftType { get; set; }
        public System.DateTime FirstInTime { get; set; }
        public System.DateTime FirstOutTime { get; set; }
        public Nullable<System.DateTime> SecondInTime { get; set; }
        public Nullable<System.DateTime> SecondOutTime { get; set; }
        public Nullable<System.DateTime> LunchStartTime { get; set; }
        public Nullable<System.DateTime> LunchEndTime { get; set; }
        public Nullable<System.DateTime> LunchTime { get; set; }
        public Nullable<bool> LunchTimeExcludeFlag { get; set; }
        public System.DateTime WorkingHours { get; set; }
        public Nullable<bool> NightShiftFlag { get; set; }
        public int BranchId { get; set; }
        public int ShiftId { get; set; }
        public int MarkedAsDelete { get; set; }
        public Nullable<bool> IsOutPunchInNextDay { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
