//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCommanData
    {
        public string EmployeeCode { get; set; }
        public System.DateTime CmnDate { get; set; }
        public System.DateTime CmnTime { get; set; }
        public Nullable<int> DeviceNo { get; set; }
        public string Status { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceEmployeeCode { get; set; }
    }
}
