//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadDocument
    {
        public int DocID { get; set; }
        public int EmployeeID { get; set; }
        public string DocContentType { get; set; }
        public string DocType { get; set; }
        public string DocDescription { get; set; }
        public string DocStatus { get; set; }
        public string ExtraDetails { get; set; }
        public string DocPath { get; set; }
        public string DocFolder { get; set; }
        public string FileName { get; set; }
    }
}
