//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int EmployeeId { get; set; }
        public int RoleTypeId { get; set; }
        public string Status { get; set; }
        public string LocationList { get; set; }
        public string CompanyList { get; set; }
        public string BranchList { get; set; }
        public string DepartmentList { get; set; }
        public string MenuId { get; set; }
        public string MastersRights { get; set; }
        public string AttendanceRights { get; set; }
        public string ApplicationsRights { get; set; }
        public string SanctionsRights { get; set; }
        public string ReportsRights { get; set; }
        public string AdministrationRights { get; set; }
        public string UpdatesRights { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public string DivisionList { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
    }
}
