//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWREPORT
    {
        public int DailyTrnId { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public int EmployeeTypeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> Leavingdate { get; set; }
        public System.DateTime TranDate { get; set; }
        public string ShiftId { get; set; }
        public System.DateTime Login { get; set; }
        public System.DateTime LogOut { get; set; }
        public Nullable<System.DateTime> Early { get; set; }
        public Nullable<System.DateTime> Late { get; set; }
        public Nullable<System.DateTime> WorkingHrs { get; set; }
        public Nullable<System.DateTime> ExtraHrs { get; set; }
        public string SanctionedCOHrs { get; set; }
        public string Status { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public string EmployeeTypeName { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string GradeName { get; set; }
        public Nullable<int> LateCount { get; set; }
        public string ReportingPersonName { get; set; }
        public string Gender { get; set; }
    }
}
