//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_CompOffApplicationIndex
    {
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<int> FromDateStatus { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> ToDateStatus { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ExtrasHoursDate { get; set; }
        public string RejectReason { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Text { get; set; }
        public int MarkedAsDelete { get; set; }
        public int CompOffId { get; set; }
        public string EmployeeCode { get; set; }
    }
}
