//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwLeaveApplicationIndex
    {
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public int LeaveApplicationId { get; set; }
        public int EmployeeId { get; set; }
        public string LeaveType { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<int> FromDayStatus { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> ToDayStatus { get; set; }
        public Nullable<double> AppliedDays { get; set; }
        public Nullable<double> ActualDays { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> Status { get; set; }
        public string RejectReason { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public string Text { get; set; }
        public int MarkedAsDelete { get; set; }
        public Nullable<bool> IsLWP { get; set; }
        public Nullable<double> LWP { get; set; }
        public Nullable<double> TotalDeductableDays { get; set; }
        public Nullable<double> LeaveConsumed { get; set; }
        public Nullable<bool> IsPreSandwichCase { get; set; }
        public Nullable<double> PreSandwichdays { get; set; }
        public Nullable<double> PostSandwichdays { get; set; }
        public Nullable<int> PreSandwichCaseLeaveID { get; set; }
        public Nullable<int> PostSandwichCaseLeaveID { get; set; }
    }
}
