//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwLocationNameInCompany
    {
        public string CompanyName { get; set; }
        public int CompanyId { get; set; }
        public int LocationId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Email { get; set; }
        public string PAN { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string LocationName { get; set; }
        public int MarkedAsDelete { get; set; }
        public string City { get; set; }
        public string PINCode { get; set; }
    }
}
