//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwNewsList
    {
        public int NewsId { get; set; }
        public string Type { get; set; }
        public string Info { get; set; }
        public System.DateTime NewsDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> EmployeeGroupId { get; set; }
        public string NewsFor { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> NewsEndDate { get; set; }
        public string BranchName { get; set; }
        public string CompanyName { get; set; }
        public string EmployeeGroupName { get; set; }
    }
}
