//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwRuleTransaction
    {
        public string Formula { get; set; }
        public string SubCode { get; set; }
        public string HeadCode { get; set; }
        public string Active { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public int EmployeeGroupId { get; set; }
        public int RuleTransId { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
        public int Expr3 { get; set; }
        public string RuleName { get; set; }
        public string CompanyName { get; set; }
        public string BranchName { get; set; }
        public string EmployeeGroupName { get; set; }
    }
}
